FROM node:14.18.1-alpine as build
WORKDIR /app
COPY ../../app/package.json .
RUN npm install
COPY ../../app .
RUN npm run build

FROM nginx:1.19-alpine
COPY  --from=build /app/build /usr/share/nginx/html

